### ISSUE TITLE
Speed calculation is wrong

### ISSUE THREAD

**Issue by Codeover-Development** [Mtuart/Speedometer#1]
Hey! The velocity of the Armorstand * 20 does not lead to the correct b/s. You could use a PlayerMoveEvent instead.

``` java   
   @EventHandler
    public void onPlayerMove(PlayerMoveEvent event){
        Location start = event.getFrom().clone();
        Location end = event.getTo().clone();
        start.setY(0);
        end.setY(0);
        double finalSpeed = start.distance(end) * 20;
    }
```
    
 But still a cool add-on!

**Comment by Mtuart** [comment]
PlayerMoveEvent doesn't get called when sitting in Vehicles. I think I still have the wrong speed, as I might need to do speed-2 to get the actual speed. Also I am taking the vectors magnitude, which returns the blocks per tick. Since 1sec = 20 ticks that amount * 20 = b/s - I think it is correct, just thinking bout the -2 there... I'll check tomorrow though.

**Comment by Mtuart** [comment]
Alright, I have managed to work around with the EntityMoveEvent which seems to give better results? Thanks for finding this haha
